db/migrate/20170714025541_create_users.rb
db/migrate/20170714032835_create_feedbacks.rb
db/migrate/20170714033336_create_user_settings.rb
db/migrate/20170714033710_create_requests.rb
db/migrate/20170714034533_create_announcements.rb
db/migrate/20170714034629_create_settings.rb
db/migrate/20170714034854_create_notifications.rb
db/migrate/20170714035844_create_books.rb
db/migrate/20170714040124_create_tags.rb
db/migrate/20170714040130_create_book_tags.rb
db/migrate/20170714040516_create_publishers.rb
db/migrate/20170714041037_create_book_items.rb
db/migrate/20170714041247_create_categories.rb
db/migrate/20170714041400_create_book_categories.rb
db/migrate/20170714041624_create_series.rb
db/migrate/20170714041940_create_images.rb
db/migrate/20170714042237_create_languages.rb
db/migrate/20170714042558_create_rates.rb
db/migrate/20170714042633_create_borrows.rb
db/migrate/20170714043157_create_follows.rb
db/migrate/20170714043332_create_author_books.rb
db/migrate/20170714043757_create_blogs.rb
db/migrate/20170714043903_create_blog_books.rb
db/migrate/20170714044752_create_votes.rb
db/migrate/20170714045207_create_comments.rb
db/migrate/20170715051702_create_authors.rb
db/migrate/20170715094112_create_suggest_books.rb
db/migrate/20170715094651_create_ebooks.rb
db/schema.rb

126937: データベースを作成する

---

app/models/admin.rb
app/models/announcement.rb
app/models/author.rb
app/models/author_book.rb
app/models/blog.rb
app/models/blog_book.rb
app/models/book.rb
app/models/book_category.rb
app/models/book_item.rb
app/models/book_tag.rb
app/models/borrow.rb
app/models/category.rb
app/models/comment.rb
app/models/ebook.rb
app/models/feedback.rb
app/models/follow.rb
app/models/image.rb
app/models/language.rb
app/models/notification.rb
app/models/publisher.rb
app/models/rate.rb
app/models/request.rb
app/models/series.rb
app/models/setting.rb
app/models/suggest_book.rb
app/models/tag.rb
app/models/user.rb
app/models/user_setting.rb
app/models/vote.rb

126938-全部のモデルを作成しました。

---

.gitignore
config/environments/development.rb
config/initializers/config.rb
config/initializers/devise.rb

126939-パスワードをお忘れる

---

app/helpers/application_helper.rb
app/views/admin/layouts/_footer.html.erb
app/views/admin/layouts/_header.html.erb
app/views/admin/layouts/_sidebar.html.erb
app/views/admin/static_pages/dashboard.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
config/application.rb
config/locales/en.yml
config/locales/layouts/en.yml

128057-I18n

---

Gemfile
Gemfile.lock
app/assets/javascripts/users/layouts/header.js
app/assets/stylesheets/users/_colors.scss
app/assets/stylesheets/users/layouts/header.scss
app/controllers/search_controller.rb
app/models/book.rb
app/views/layouts/_header.html.erb
app/views/search/_autocomplete.html.erb
app/views/search/index.html.erb
config/locales/layouts/en.yml
config/routes.rb
config/settings.yml

126960 本を検査する１　カテゴリー、タグによる

---

.rubocop_enabled.yml
Gemfile.lock
app/assets/javascripts/users/book.js
app/assets/stylesheets/application.css
app/assets/stylesheets/users/_colors.scss
app/assets/stylesheets/users/book.scss
app/controllers/books_controller.rb
app/helpers/books_helper.rb
app/models/blog.rb
app/models/book.rb
app/models/comment.rb
app/views/books/_book_center.html.erb
app/views/books/_book_left.html.erb
app/views/books/_book_right.html.erb
app/views/books/_social.html.erb
app/views/books/show.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20170717062328_add_rate_and_rate_count_to_books.rb
db/migrate/20170717093231_remove_type_from_images.rb
db/migrate/20170717113155_add_description_to_books.rb
db/migrate/20170718020258_remove_type_from_comments.rb
db/schema.rb

126957 本の詳細な情報を見る

---

Gemfile.lock
app/assets/javascripts/admin/category.js
app/assets/stylesheets/admin/categories.scss
app/assets/stylesheets/admin/users.scss
app/controllers/admin/categories_controller.rb
app/controllers/admin/users_controller.rb
app/models/supports/admin_categories.rb
app/views/admin/categories/_categories.html.erb
app/views/admin/categories/_category_modal.html.erb
app/views/admin/categories/index.html.erb
app/views/admin/categories/index.js.erb
app/views/admin/users/_user_modal.html.erb
app/views/admin/users/_users.html.erb
app/views/admin/users/index.js.erb
config/locales/admin/categories/en.yml
config/routes.rb
config/settings.yml
db/schema.rb
db/seeds.rb

#126945: カテゴリー管理２/２

---

app/assets/stylesheets/users/_colors.scss
app/assets/stylesheets/users/categories.scss
app/assets/stylesheets/users/explorer.scss
app/controllers/categories_controller.rb
app/controllers/explorer_controller.rb
app/models/category.rb
app/views/categories/_book.html.erb
app/views/categories/_sidebar.html.erb
app/views/categories/show.html.erb
app/views/explorer/index.html.erb
app/views/layouts/_header.html.erb
config/locales/categories/en.yml
config/locales/explorer/en.yml
config/locales/layouts/en.yml
config/routes.rb
config/settings.yml

126953 本をリスト , フィルタする (renew) part 1

---

app/assets/stylesheets/users/tags.scss
app/controllers/categories_controller.rb
app/controllers/tags_controller.rb
app/models/tag.rb
app/views/tags/show.html.erb
config/locales/tags/en.yml
config/routes.rb

126953 - show book by tag - 1

---

Gemfile
Gemfile.lock
app/assets/javascripts/users/categories.js
app/assets/javascripts/users/layouts/header.js
app/assets/javascripts/users/tags.js
app/assets/stylesheets/users/categories.scss
app/controllers/categories_controller.rb
app/controllers/tags_controller.rb
app/helpers/application_helper.rb
app/views/categories/_sidebar.html.erb
app/views/categories/index.html.erb
app/views/explorer/index.html.erb
app/views/tags/index.html.erb
app/views/tags/show.html.erb
config/locales/categories/en.yml
config/locales/tags/en.yml

126956 本をフィルタする

---

app/assets/javascripts/users/blog/posts.js
app/assets/stylesheets/application.css
app/assets/stylesheets/users/_colors.scss
app/assets/stylesheets/users/blog/dashboard.scss
app/assets/stylesheets/users/blog/posts.scss
app/controllers/blog/dashboard_controller.rb
app/controllers/blog/posts_controller.rb
app/controllers/books_controller.rb
app/models/blog.rb
app/models/user.rb
app/views/blog/dashboard/index.html.erb
app/views/blog/posts/edit.html.erb
app/views/layouts/_header.html.erb
config/locales/blog/en.yml
config/routes.rb
config/settings.yml
db/migrate/20170727080025_add_status_to_blog.rb
db/schema.rb
package.json
yarn.lock

読んだ本の感想を会社のBlog機能ビュー（index, new, edit, update）

---

.gitignore
app/assets/javascripts/users/blog/posts.js
app/assets/stylesheets/users/blog/posts.scss
app/controllers/blog/posts_controller.rb
app/helpers/blog/posts_helper.rb
app/views/blog/dashboard/index.html.erb
app/views/blog/posts/_new_post_form.html.erb
app/views/blog/posts/index.html.erb
app/views/blog/posts/show.html.erb
app/views/layouts/_header.html.erb
config/locales/blog/en.yml

読んだ本の感想を会社のBlogのバックエンド（index, show）

---

app/assets/javascripts/admin/category.js
app/assets/javascripts/admin/requests.js
app/assets/stylesheets/admin/borrow_books.scss
app/assets/stylesheets/admin/borrows.scss
app/controllers/admin/requests_controller.rb
app/models/book_item.rb
app/models/borrow.rb
app/models/supports/admin_requests.rb
app/views/admin/layouts/_sidebar.html.erb
app/views/admin/requests/_borrow.html.erb
app/views/admin/requests/_requests.html.erb
app/views/admin/requests/index.html.erb
app/views/admin/requests/index.js.erb
config/locales/admin/layouts/en.yml
config/locales/admin/requests/en.yml
config/routes.rb
db/seeds.rb

本を借りることを管理する
・本を借りるかどうかを承認する。
・本を借りる情報を表す。

126968：本を借りることを管理する

---

.rubocop_disabled.yml
app/assets/javascripts/users/books.js
app/assets/javascripts/users/static_pages.js
app/assets/stylesheets/users/_colors.scss
app/assets/stylesheets/users/book.scss
app/assets/stylesheets/users/books/comments.scss
app/assets/stylesheets/users/categories.scss
app/assets/stylesheets/users/home.scss
app/assets/stylesheets/users/layouts/header.scss
app/controllers/admin/requests_controller.rb
app/controllers/borrows_controller.rb
app/controllers/static_pages_controller.rb
app/helpers/static_pages_helper.rb
app/models/author.rb
app/models/blog.rb
app/models/book.rb
app/models/book_item.rb
app/models/borrow.rb
app/models/supports/admin_requests.rb
app/views/books/_book_center.html.erb
app/views/books/_book_left.html.erb
app/views/books/_book_right.html.erb
app/views/books/_comment_form.html.erb
app/views/books/_related_book.html.erb
app/views/books/show.html.erb
config/locales/en.yml

126966 本を借りる

---

app/assets/stylesheets/users/layouts/header.scss
app/controllers/admin/requests_controller.rb
app/views/categories/_book.html.erb
app/views/categories/_sidebar.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/explorer/index.html.erb
app/views/tags/index.html.erb
app/views/tags/show.html.erb
config/locales/devise.en.yml
config/locales/explorer/en.yml

fix style login screen

---

app/assets/javascripts/users/authors.js
app/assets/javascripts/users/static_pages.js
app/assets/stylesheets/admin/_colors.scss
app/assets/stylesheets/admin/layouts/sidebar.scss
app/assets/stylesheets/users/authors.scss
app/controllers/authors_controller.rb
app/views/authors/show.html.erb
app/views/books/_book_center.html.erb
app/views/books/_related_book.html.erb
app/views/static_pages/_book_slide_item.html.erb
app/views/static_pages/_hot_book.html.erb
config/locales/en.yml
config/routes.rb

------------------------------------------
[o] Build Success!
------------------------------------------
[o] brakeman: success
[o] eslint: success
[o] rspec: success
[o] rubocop: success
[o] scss-lint: success
[o] reek: success
[o] bundle-audit: success
[o] rails_best_practices: success

130791 著者の情報をショーする

---

app/assets/javascripts/users/books.js
app/assets/stylesheets/users/book.scss
app/controllers/not_found_controller.rb
app/controllers/read_online_controller.rb
app/views/books/_book_center.html.erb
app/views/books/_social.html.erb
app/views/books/show.html.erb
config/locales/en.yml

借用時間が180日を超えないことを確認するし、画面に反応します。
)![phone2](https://user-images.githubusercontent.com/16103158/28903687-9178c8a0-7830-11e7-9c4c-0d7869d8f10e.png)
CI:
------------------------------------------
[o] Build Success!
------------------------------------------
[o] brakeman: success
[o] scss-lint: success
[o] rails_best_practices: success
[o] reek: success
[o] rubocop: success
[o] rspec: success
[o] eslint: success
[o] bundle-audit: success

131130 本の具体的なページを直す

---

app/assets/javascripts/users/static_pages.js
app/assets/stylesheets/users/home.scss
app/views/static_pages/_hot_author.html.erb
app/views/static_pages/_hot_book.html.erb

------------------------------------------
[o] Build Success!
------------------------------------------
[o] brakeman: success
[o] scss-lint: success
[o] rspec: success
[o] rubocop: success
[o] eslint: success
[o] reek: success
[o] bundle-audit: success
[o] rails_best_practices: success

131250 ホームページのスライドを直す　

---

app/assets/javascripts/users/authors.js
app/assets/javascripts/users/books.js
app/assets/stylesheets/users/book.scss
app/views/books/_book_center.html.erb
app/views/books/_book_right.html.erb
app/views/books/_popup_author_info.html.erb
config/settings.yml

131446 本のページでポップアップを追加する

---

app/assets/javascripts/admin/requests.js
app/assets/stylesheets/users/_colors.scss
app/assets/stylesheets/users/announcements.scss
app/controllers/admin/requests_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/announcements_controller.rb
app/controllers/blog/posts_controller.rb
app/views/announcements/_announcement.html.erb
app/views/announcements/_announcements.html.erb
app/views/announcements/index.html.erb
app/views/blog/dashboard/index.html.erb
app/views/blog/posts/index.html.erb
app/views/blog/posts/show.html.erb
app/views/categories/_book.html.erb
app/views/layouts/_header.html.erb
app/views/search/_autocomplete.html.erb
config/locales/blog/en.yml
config/locales/layouts/en.yml
db/migrate/20170809072957_remove_admin_id_from_notification.rb
db/schema.rb

hotfix announcaments, blog, navbar

---

app/assets/javascripts/users/layouts/header.js
app/assets/stylesheets/users/layouts/header.scss
app/controllers/feedback_controller.rb
app/views/feedback/_modal.html.erb
app/views/layouts/_header.html.erb
config/locales/feedback/en.yml
config/locales/layouts/en.yml
config/routes.rb
db/migrate/20170714032835_create_feedbacks.rb
db/seeds.rb

132589 ユーザーのフィードバック

---

app/assets/javascripts/users/layouts/header.js
app/assets/stylesheets/users/layouts/header.scss
app/views/feedback/_modal.html.erb

hotfix feedback modal close after 3s

---

app/assets/javascripts/users/blog/posts.js
app/assets/javascripts/users/books.js
app/controllers/notifications_controller.rb
app/controllers/votes_controller.rb
app/helpers/application_helper.rb
app/views/books/_book_center.html.erb
app/views/books/_child_comments.html.erb
app/views/books/_comments.html.erb
app/views/layouts/_footer.html.erb
config/routes.rb

Vote comment, fix blog bug

---

app/assets/javascripts/users/static_pages.js
app/assets/stylesheets/users/_colors.scss
app/assets/stylesheets/users/home.scss
app/assets/stylesheets/users/layouts/header.scss
app/controllers/static_pages_controller.rb
app/models/book.rb
app/models/supports/home.rb
app/views/layouts/_footer.html.erb
app/views/static_pages/_hot_book.html.erb
app/views/static_pages/home.html.erb
config/locales/en.yml
config/routes.rb
config/settings.yml

ホームのバックグラウンドと新しい本のアルゴリズム

---

app/assets/javascripts/users/blog/posts.js
app/assets/javascripts/users/books.js
app/assets/stylesheets/users/blog/posts.scss
app/assets/stylesheets/users/not_found.scss
app/controllers/blog/comments_controller.rb
app/controllers/blog/posts_controller.rb
app/controllers/blog/votes_controller.rb
app/controllers/categories_controller.rb
app/controllers/comments_controller.rb
app/models/blog.rb
app/views/blog/dashboard/index.html.erb
app/views/blog/posts/_child_comments.html.erb
app/views/blog/posts/_child_comments_form.html.erb
app/views/blog/posts/_comment_form.html.erb
app/views/blog/posts/_comments.html.erb
app/views/blog/posts/index.html.erb
app/views/blog/posts/show.html.erb
app/views/books/_social.html.erb
app/views/not_found/index.html.erb
config/locales/not_found/en.yml
config/routes.rb
db/schema.rb
db/seeds.rb

Add comment blog

---

app/assets/stylesheets/users/blog/dashboard.scss
app/controllers/blog/dashboard_controller.rb
app/models/book.rb
app/models/book_item.rb
app/models/user.rb
app/views/blog/dashboard/index.html.erb
app/views/blog/posts/index.html.erb
config/locales/blog/en.yml

blog-recommendation
